### PR TITLE
Switched to api.fixer.io, removed calculations, added tests

### PR DESCRIPTION
**Pull request by MichaelTSS**
Hey,

I'm fairly new to Go, please tell me what you think could be written better.

So I read your thread on Reddit (i_am_square here) and initially wanted to switch to an API that does support the right currencies for the right countries. There is much less information likes countries, and currency name, but this API has fantastic uptime.

Please give me your feedback, for the design as well as coding matters.

I dropped the CurrencyConverter for the sake of having a mergable PR, I am unsure if it should be even there in the first place, it would make the utility a bit smaller. If you decide to leave it as it, perhaps recommend shopspring/decimal on the Readme.md?

Cheers,

### CODE REVIEW

**Comment by d6o** [comment]
Nice!!! 
Thank you for your contribution! 

I will take a look at night!

**Comment by MichaelTSS** [comment]
Once this repo is solid enough, you could make a PR to add your utility in the financial section of this repo : https://github.com/avelino/awesome-go

**Comment by MichaelTSS** [comment]
There are over 160 currencies according to xe.com and that doesn't count crypto currencies. Maybe api.fixer.com isn't the best choice after all

**Comment by MichaelTSS** [comment]
Hello @DiSiqueira any news?

**Comment by d6o** [comment]
Hi @MichaelTSS sorry about the delay!
Your implementation are really good, thank you about this!!

Can you please just update the examples on README file?

**Pull request merged**
